GoldenrodCity_MapScripts::
	.byte 0

GoldenrodTest_GiveItems::
	additem ITEM_PURPLE_APRICORN
	additem ITEM_CYAN_APRICORN
	additem ITEM_LIME_APRICORN
	additem ITEM_ORANGE_APRICORN
	additem ITEM_GRAY_APRICORN
	additem ITEM_GOLD_APRICORN
	additem ITEM_ICE_CRYSTAL
	additem ITEM_ELEC_CRYSTAL
	additem ITEM_FIRE_CRYSTAL
	additem ITEM_MAGNET_PASS
	additem ITEM_SILVER_PASS
	additem ITEM_BUENAS_PIN
	additem ITEM_0F9
	additem ITEM_0FA
	additem ITEM_RAINBOW_WING
	additem ITEM_SILVER_WING
	additem ITEM_NATIONAL_PASS
	release
	end
